name: Labeler
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler-config.yml
